### PR TITLE
Remove reporting requirement around criminal behaviour in definition …

### PR DESCRIPTION
**Pull request by mjg59**
Remove reporting requirement around criminal behaviour in definition of uncivil
    
Reporting an individual to law enforcement may put that individual's life in
danger, no matter how insignificant the perceived criminal behaviour. Remove
the requirement that authorities be contacted before this can be taken into
account when determining that someone may be uncivil.

### CODE REVIEW

**Comment by jdegoes** [comment]
@mjg59 It is neither stated nor intended that a potential _victim_ must report such behavior. But if there is a potential danger to someone or some class of individuals (e.g. someone advocating genocide, someone making threats against someone else, etc.), then a community that knows of this danger but fails to report it to authorities could be guilty of accessory and open to civil lawsuit.

I think the proper fix for #104 would make it explicit this requirement can be waived explicitly (even though I would never recommend it).

**Comment by mjg59** [comment]
It doesn't matter whether it's a _victim_ who reports it or not, the fact remains that in certain jurisdictions (including parts of the US) reporting an individual to law enforcement carries a real risk that that individual will be killed. An individual may break the law in such a way that a community may feel that that individual should be pre-emptively blocked from entering the community, but not in such a way that the community feels that that individual should be put at risk of being killed[1]. It should be up to that community to make their own determination about whether they're willing to accept any associated legal risks, and the CoC shouldn't default to requiring reporting in order to be able to take action.

[1] eg: a security research community may not wish to permit individuals who breach the CFAA to become members as doing so may harm the community's goals, but may not wish to put them in a situation where they're at risk of being killed by law enforcement or being deported to a hostile state with a record of human rights abuses

**Comment by jdegoes** [comment]
@mjg59 I'll discuss with a lawyer on this point. I will say it's beyond the scope of a COC to assume that law enforcement is going to come and kill you, or that a community must break the law.

**Comment by mk-pmb** [comment]
Over the years I've read about quite a few laws where it's hard to predict whether courts will consider a certain behavior as criminal, and some laws where common sense indicates it shouldn't be criminal. Sometimes they even violate the constitution quite obviously but the highest courts still need a long time to officially confirm the violation.

> to assume that law enforcement is going to come and kill you,

That's not required. In some unfortunate edge cases, just putting people on record can facilitate follow-up illegal action by non-officers, including honor killings. I won't try and find again the documentaries or articles from which I heard about such cases, and instead offer a more general argument:
As I see it, any assumption about how the legal system in a certain area operates, restricts the range for which communities FCOP works, so we should reduce those assumptions to a minimum.

**Comment by mjg59** [comment]
This was closed, but the issue doesn't appear to have been fixed.

**Pull request closed without merging**
